In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import torch

In [5]:
input_dir = "/home/schidara-dev/repos/learningrepos/makemore/"
names_file = "names.txt"

In [19]:
with open(input_dir+names_file, "r") as f:
    names_lines = f.readlines()

In [20]:
names_lines = [line.strip() for line in names_lines]

In [22]:
names_lines[:3]

['emma', 'olivia', 'ava']

In [25]:
a = torch.zeros(3,5)
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [26]:
a.dtype

torch.float32

In [28]:
a = torch.zeros(3, 5, dtype=torch.int32)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [30]:
a[1, 3] = 5
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 5, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)